# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio station | Vladimir Shepel
email: web.shepel@gmail.com
description: Beautiful web design, UI elements, templates, redesigns etc.
url: "http://vowwwa.com" # the base hostname & protocol for your site
twitter_username: vshepel
github_username:  vshepel

# Build settings
markdown: kramdown

permalink: /works/:categories/:title.html

#gems:
#  - octopress-minify-html
future: true
